[application]

[bundle]
identifier = "com.tangxiangong.bibcitex.app"
publisher = "tangxiangong"
icon = [
    "assets/icons/32x32.png",
    "assets/icons/128x128.png",
    "assets/icons/128x128@2x.png",
    "assets/icons/icon.icns",
    "assets/icons/icon.ico",
]


[web.app]

# HTML title tag content
title = "BibCiTeX"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
